# Default values
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
rbacEnabled: true
namespace: dev-test

image:
  repository: a6s-k8s-keycloak-manager
  tag: 0.0.1
  pullPolicy: IfNotPresent
  pullSecrets:

volumes:
  persistentVolumeClaim:
   # - name: pvc-name
   #   mountPath: /var/pvc
  configMap:
   # - name: config-map-name
   #   mountPath: /var/config
  secret:
   # - name: secret-name
   #   mountPath: /var/secret

env:
  NODE_ENV: production

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

persistence:
  enabled: false
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:

  ## service data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 8Gi

nodeSelector: {}

tolerations: []

affinity: {}
