keycloak:
  server_url: http://localhost:30800/auth
  
  masterRealm: master
  realm: master
  
  # Key/value pairs of all custom client attributes.
  # This attributes will be added to all created clients and will be used to load from Keycloak
  # upon merging - upon start keycloak manager will load all resources and compare them with clients 
  # registered on Keycloak. Only clients with given attributes will be used for merging.
  #clientAttributes: 
  #  name: value
  
  auth:
    username: 'admin'
    password: 'admin'
    grantType: 'password'
    clientId: 'admin-cli'
    clientSecret: 'adf8ab97-0566-407a-bbf3-e9dc0878d56a'

log4js:
  appenders:
    default:
      type: console
  categories:
    default:
      appenders:
        - default
      level: debug

k8s:
  namespaces:
    - default
  resource:
    name: keycloakclients
    apiVersion: apigeeks.com/v1
