keycloak:
  server_url: http://localhost:30800/auth
  masterRealm: master
  realm: master
  clientAttributes:
    foo: boo
  auth:
    username: 'admin'
    password: 'admin'
    grantType: 'password'
    clientId: 'admin-cli'
    clientSecret: 'adf8ab97-0566-407a-bbf3-e9dc0878d56a'

log4js:
  appenders:
    default:
      type: console
  categories:
    default:
      appenders:
        - default
      level: debug

k8s:
  namespaces:
    - default
  resource:
    name: keycloakclients
    apiVersion: apigeeks.com/v1
